services:
  # 1. KHQR Bakong Python Microservice
  - type: web
    name: mlbb-khqr-api
    runtime: docker
    dockerContext: ./Scorekhqr-bakong
    dockerfilePath: ./Scorekhqr-bakong/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "5001"
      - key: DEMO_MODE
        value: "false"
      - key: MERCHANT_BAKONG_ID
        value: "deth_peak3@aclb"
      - key: MERCHANT_NAME
        value: "PuDeth Smart-PAY"
      - key: MERCHANT_CITY
        value: "PHNOM PENH"
      - key: ACQUIRING_BANK
        value: "FAMILY PHONE"
      - key: BAKONG_TOKEN
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiYzY4NGNhNTUwNTJmNDRjYiJ9LCJpYXQiOjE3ODcwNTkwNTIsImV4cCI6MTc5NDgzNTA1Mn0.IOaSl7-TRdyrTjWM7mQMaaaAUP0E7N7zgtX-AsPZPLE"
      - key: TELEGRAM_BOT_TOKEN
        value: "8516986555:AAH3enGgrbjWPKnQRPwXRQHKVfGgqiQ2Rhw"
      - key: TELEGRAM_CHAT_ID
        value: "-5216036558"
      - key: MONGODB_URI
        value: "mongodb+srv://peakmao007_db_user:DNelqTteMX30a7PX@pudeth.olrum6s.mongodb.net/?appName=pudeth&retryWrites=true&w=majority"

  # 2. ASP.NET Core 8 Web API Backend
  - type: web
    name: mlbb-backend-api
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: "http://0.0.0.0:10000"
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        value: "mongodb+srv://peakmao007_db_user:DNelqTteMX30a7PX@pudeth.olrum6s.mongodb.net/?appName=pudeth&retryWrites=true&w=majority"
      - key: KHQR__ApiUrl
        fromService:
          type: web
          name: mlbb-khqr-api
          property: host
