services:
  # 1. KHQR Bakong Python Microservice
  - type: web
    name: mlbb-khqr-api
    runtime: docker
    dockerContext: ./Scorekhqr-bakong
    dockerfilePath: ./Scorekhqr-bakong/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: DEMO_MODE
        value: "false"
      - key: MONGODB_URI
        value: "mongodb+srv://peakmao007_db_user:DNelqTteMX30a7PX@pudeth.olrum6s.mongodb.net/?appName=pudeth&retryWrites=true&w=majority"

  # 2. ASP.NET Core 8 Web API Backend
  - type: web
    name: mlbb-backend-api
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MONGODB_URI
        value: "mongodb+srv://peakmao007_db_user:DNelqTteMX30a7PX@pudeth.olrum6s.mongodb.net/?appName=pudeth&retryWrites=true&w=majority"
      - key: KHQR__ApiUrl
        fromService:
          type: web
          name: mlbb-khqr-api
          property: host
