import requests
import json
import time

BASE_URL = "http://localhost:5000/api/PayWay"

def test_generate_qr():
    print("\n--- Testing Generate QR API ---")
    payload = {
        "orderId": int(time.time()),
        "amount": 0.05
    }
    try:
        res = requests.post(f"{BASE_URL}/generate-qr", json=payload)
        data = res.json()
        print("Response from ABA Sandbox:")
        print(f"Status Code: {data.get('status', {}).get('code')}")
        print(f"Status Message: {data.get('status', {}).get('message')}")
        print(f"Amount: {data.get('amount')} {data.get('currency')}")
        if data.get('qrString'):
            print("Successfully received QR String!")
        if data.get('qrImage'):
            print("Successfully received Base64 QR Image!")
    except Exception as e:
        print("Error calling generate-qr:", str(e))

def test_link_card():
    print("\n--- Testing Link Card API ---")
    payload = {
        "ctid": "USER_TEST_123"
    }
    try:
        res = requests.post(f"{BASE_URL}/link-card", json=payload)
        data = res.json()
        print("Response generated by Backend (ready to render HTML form):")
        print(f"Success: {data.get('success')}")
        print(f"Purchase URL: {data.get('purchaseUrl')}")
        print(f"Tran ID: {data.get('tranId')}")
        print(f"Form Data Hash: {data.get('formData', {}).get('hash')}")
    except Exception as e:
        print("Error calling link-card:", str(e))

def test_link_account():
    print("\n--- Testing Link Account API ---")
    payload = {
        "ctid": "USER_TEST_123"
    }
    try:
        res = requests.post(f"{BASE_URL}/link-account", json=payload)
        data = res.json()
        print("Response from ABA Sandbox:")
        print(f"Status Code: {data.get('status', {}).get('code')}")
        print(f"Status Message: {data.get('status', {}).get('message')}")
        if data.get('qrString'):
            print("Successfully received QR String for ABA Account Linking!")
        if data.get('abapay_deeplink'):
            print(f"Successfully received Deeplink!")
    except Exception as e:
        print("Error calling link-account:", str(e))

if __name__ == "__main__":
    print("Initiating Sandbox API Tests against Local Backend...\n")
    test_generate_qr()
    test_link_card()
    test_link_account()
    print("\nSandbox testing sequence completed.")
